import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { JSDOM } from 'jsdom';
import { Game } from '../src/game/game.js';
import { Interface } from '../src/ui/interface.js';
import { SaveManager } from '../src/save/storage.js';
import { createItem } from '../src/equipment/items.js';
function setup(){const dom=new JSDOM(fs.readFileSync(new URL('../index.html',import.meta.url),'utf8'),{url:'https://game.test/'});globalThis.window=dom.window;globalThis.document=dom.window.document;globalThis.localStorage=dom.window.localStorage;const g=new Game();g.save=new SaveManager(dom.window.localStorage);g.input={reset(){},vector:()=>({x:0,z:0})};const ui=new Interface(g);return{g,ui,dom}}
const click=(root,text)=>{const b=[...root.querySelectorAll('button')].find(b=>b.textContent===text);assert(b,`button ${text}`);b.click()};
test('Main menu, character selection and playable state are connected',()=>{const{g,ui,dom}=setup();assert(document.querySelector('.title-screen'));click(document,'开始旅程   →');assert.equal(document.querySelector('.panel h2').textContent,'选择行者');ui.fullscreen=()=>{};click(document,'以此角色开始');assert.equal(g.state,'PLAYING');assert.equal(document.querySelector('#hud').hidden,false);clearTimeout(ui.toastTimer);dom.window.close()});
test('Settings inputs retain handlers, apply and preserve an existing run',()=>{const{g,ui,dom}=setup();g.start();g.player.gold=123;g.persist();ui.main();ui.open('settings');const sliders=[...document.querySelectorAll('input[type=range]')];assert(sliders.length>=6);const music=[...document.querySelectorAll('label')].find(l=>l.textContent==='音乐').querySelector('input');music.value='.1';music.dispatchEvent(new dom.window.Event('input'));assert.equal(g.settings.music,.1);assert.equal(g.save.read().run.player.gold,123);assert.equal(g.save.read().settings.music,.1);clearTimeout(ui.toastTimer);dom.window.close()});
test('Inventory detail, equip, comparison, lock and unequip work through UI',()=>{const{g,ui,dom}=setup();g.start();const item=createItem(g.rng,3,4);g.player.inventory.push(item);ui.open('inventory');document.querySelector('.item').click();assert(document.querySelector('.stat-list'));click(document,'装备');assert.equal(g.player.equipped[item.slot].id,item.id);ui.open('character');const slot=[...document.querySelectorAll('.slots button')].find(b=>b.textContent.includes(item.name));slot.click();click(document,'锁定');assert.equal(item.locked,true);assert.equal([...document.querySelectorAll('button')].find(b=>b.textContent==='丢到地面').disabled,true);click(document,'卸下');assert.equal(g.player.inventory.length,1);clearTimeout(ui.toastTimer);dom.window.close()});
test('All pause panels render and closing them restores gameplay',()=>{const{g,ui,dom}=setup();g.start();for(const tab of ['pause','character','inventory','skills','boons','codex','map','settings','shop','event']){ui.open(tab);assert.equal(g.state,'PAUSED');assert(document.querySelector('.panel h2').textContent);ui.close();assert.equal(g.state,'PLAYING')}clearTimeout(ui.toastTimer);dom.window.close()});
